{% set version = "9.3" %}

package:
  name: or-tools-package
  version: {{ version }}

source:
  url: https://github.com/google/or-tools/archive/v{{ version }}.tar.gz
  sha256: 6fe981326563136fbb7a697547dc0fe6495914b5b42df559c2d88b35f6bcc661

# The meta package

build:
  number: 0
  skip: true  # [not linux]

outputs:
  # The core package
  - name: ortools-cpp
    script: build-cpp.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.18
        # Source: https://github.com/google/or-tools/blob/stable/cmake/python.cmake#L6
        - git
        - make
        - pkg-config
      host:
        - libabseil
        - libprotobuf
        - re2
        - zlib
        # coin or deps
        - coin-or-utils
        - coin-or-osi
        - coin-or-clp
        - coin-or-cgl
        - coin-or-cbc
        # Source: https://github.com/google/or-tools/blob/stable/cmake/dependencies/CMakeLists.txt
        - python
      run_constrained:
        - scip =7.0.1

    test:
      commands:
        - test -f $PREFIX/lib/libortools${SHLIB_EXT}
        - test -f $PREFIX/lib/cmake/ortools/ortoolsTargets.cmake
        - test -f $PREFIX/lib/cmake/ortools/ortoolsConfig.cmake
        - test -f $PREFIX/include/ortools_export.h
        - test -f $PREFIX/include/ortools/algorithms/dense_doubly_linked_list.h

      # The python package.
  - name: ortools-python
    script: build-python.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.18
        - git
        - make
        - mypy-protobuf
        - pkg-config
        - setuptools
        - swig >=4.0
      host:
        - libabseil
        - absl-py >=0.13
        - libprotobuf
        - numpy
        - mypy-protobuf
        - pip >=9.0.1
        - python >=3.6
        - virtualenv
        - wheel
        - zlib
        # coin or deps
        - coin-or-utils
        - coin-or-osi
        - coin-or-clp
        - coin-or-cgl
        - coin-or-cbc
      run:
        - absl-py >=0.13
        - mypy-protobuf
        - {{ pin_compatible('numpy') }}
        - protobuf
        - python >=3.6
        # Source: https://github.com/google/or-tools/blob/stable/ortools/python/setup.py.in#L44
      run_constrained:
        - scip =7.0.1

    test:
      imports:
        - ortools
        - ortools.linear_solver.pywraplp
      commands:
        - pip check
        - ${PYTHON} cmake/samples/python/sample.py
        - ${PYTHON} ortools/sat/samples/assignment_sat.py
      requires:
        - pip
      source_files:
        - cmake/samples/python/sample.py
        - ortools/sat/samples/assignment_sat.py

about:
  home: https://developers.google.com/optimization
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE-2.0.txt
  summary: Google Operations Research Tools (or-tools) python package
  description: |
    OR-Tools is an open source software suite for optimization, tuned for tackling
    the world's toughest problems in vehicle routing, flows, integer and linear
    programming, and constraint programming.

    After modeling your problem in the programming language of your choice, you
    can use any of a half dozen solvers to solve it: commercial solvers such as
    Gurobi or CPLEX, or open-source solvers such as SCIP, GLPK, or Google's GLOP
    and award-winning CP-SAT.
  dev_url: https://github.com/google/or-tools

extra:
  recipe-maintainers:
    - wolfv
    - BastianZim
    - h-vetinari
  feedstock-name: or-tools
